services:
    sg_datatables.serializer.method:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        public: true

    sg_datatables.serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        public: true

    sg_datatables.serializer:
        class: Symfony\Component\Serializer\Serializer
        public: true
        arguments:
            - ['@sg_datatables.serializer.method']
            - ['@sg_datatables.serializer.encoder.json']

    sg_datatables.twig.extension:
        class: Sg\DatatablesBundle\Twig\DatatableTwigExtension
        public: true
        arguments: ['@translator']
        tags:
            - { name: twig.extension }

    sg_datatables.datatable.abstract:
        class: Sg\DatatablesBundle\Datatable\View\AbstractDatatableView
        public: true
        abstract: true
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@translator.default'
            - '@router'
            - '@doctrine.orm.entity_manager'

    sg_datatables.query:
        alias: Sg\DatatablesBundle\Datatable\Data\DatatableDataManager
        public: true

    Sg\DatatablesBundle\Datatable\Data\DatatableDataManager:
        class: Sg\DatatablesBundle\Datatable\Data\DatatableDataManager
        public: false
        arguments:
            - '@request_stack'
            - '@sg_datatables.serializer'
            - '@twig'
            - '%sg_datatables.datatable.query%'
            - '%kernel.bundles%'
